name: End-to-end Tests
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
    env:
        CYPRESS_username: ${{secrets.username}}
        CYPRESS_password: ${{secrets.password}}
      
     